### ISSUE TITLE
zuul高级篇疑问

### ISSUE THREAD

**Issue by ghost** [ityouknow/spring-cloud-examples#12]
你好，看了你的博客：
http://www.ityouknow.com/springcloud/2018/01/20/spring-cloud-zuul.html
发现不能使用github登录，没法儿留言，所以在此提问。

将源码dow下来，修改了一下属性 试了一下，发现有这样的一个问题：
retry 只能retry到同一个实例，如果达到retry阈值后，还是会返回The service is unavailable.
期待的效果是 同一个服务 A实例 睡眠时长超过熔断时长，能retry到B实例，并返回数据.

属性配置：
ribbon.MaxAutoRetries=0
ribbon.MaxAutoRetriesNextServer=1

**Comment by ityouknow** [comment]
@AhuangLikeYou  感谢反馈，我回头确认下

**Comment by wastonhua** [comment]
同意 AhuangLikeYou 结论，多次尝试也发现这样的问题。并不能长时间、retry失败后，【始终】负载到B实例。
