### ISSUE TITLE
cannot resolve configure property feign.hystrix.enabled=true

### ISSUE THREAD

**Issue by edidada** [ityouknow/spring-cloud-examples#18]
spring-cloud-consumer-hystrix 这个工程
application.properties配置文件报错，好像是版本的问题，求答案

**Comment by 6westboy9** [comment]
![image](https://user-images.githubusercontent.com/39526241/45696290-dd2c7680-bb95-11e8-8e68-fe7094ba5f58.png)
是这样的情况吗？我配置了之后起作用了，但是为什么IDEA会报“cannot resolve...”
![image](https://user-images.githubusercontent.com/39526241/45696359-06e59d80-bb96-11e8-9705-ae20e5ef208e.png)

**Comment by doGe-personal** [comment]
请问这是什么情况呢

**Comment by 10wjfang** [comment]
用的是spring-cloud-starter-hystrix和spring-cloud-starter-openfeign，Spring Boot 2.0.3.RELEASE。Spring Cloud 版本Finchley.RELEASE，这样没问题。
