### ISSUE TITLE
怎么启动项目?

### ISSUE THREAD

**Issue by gclsoft** [ityouknow/spring-cloud-examples#22]
![image](https://user-images.githubusercontent.com/1269898/40882385-d6528f0c-6712-11e8-864b-489f5d528963.png)
右键不能运行项目, 我想整体启动看下效果,而不是一个个单个的项目

**Comment by gclsoft** [comment]
![image](https://user-images.githubusercontent.com/1269898/40888353-b0bd081e-6788-11e8-8412-c0d2393fd738.png)

**Comment by ityouknow** [comment]
都是针对微服务使用的一个一个示例

**Comment by gclsoft** [comment]
@ityouknow 启动不起来看不到效果,不能用的啊
