### ISSUE TITLE
好像用的都是spring 1.5的版本吧，怎么说是spring2.0的教程

### ISSUE THREAD

**Issue by KANLON** [ityouknow/spring-cloud-examples#41]
好像用的都是spring 1.5的版本吧，怎么说是spring2.0的教程，不过帮助真的很大，感谢作者的开源

**Comment by ityouknow** [comment]
前面十二篇是1.5的，后面的都是2.0以上，以后找机会都升级一下。

**Comment by KANLON** [comment]
感谢，因为spring cloud和spring boot1.5和spring2.0对应版本差距挺大，有很多依赖问题，之前用spring boot2.0搭建，跟着您的博客搭建spring cloud，一直搭建不起来，后来用回1.5才可以。
