### ISSUE TITLE
 Spring Cloud GateWay ERROR

### ISSUE THREAD

**Issue by qq727127158** [ityouknow/spring-cloud-examples#50]
在调试的时候发生了这样错误：
java.lang.IllegalArgumentException: Unable to find GatewayFilterFactory with name RequestRateLimiter

**Comment by little-stoner** [comment]
请问你怎么解决的？

**Comment by qq727127158** [comment]
> 请问你怎么解决的？
忘记了。。

**Comment by little-stoner** [comment]
真是，生活苦涩
