### ISSUE TITLE
调用Hystric异常，Hystric什么情况下会进入fallback

### ISSUE THREAD

**Issue by gxianch** [ityouknow/spring-cloud-examples#9]
项目由eureka server, eureka client. Hystric+Feigh 三个boot组成，eureka client作为服务，调用本地exe程序，直接通过client的端口访问，调用正常；但是通过Hystric+Feigh 转发到eureka client去调用本地exe程序，当exe在执行的时候，Hystric马上进入fallback状态，已经设置Hystric execution.timeout.enabled:false, 想了解Hystric什么情况下会进入fallback

**Comment by ityouknow** [comment]
后端出现异常的时候会进行 fallback.
